use serde::Deserialize;
use utoipa::ToSchema;
use validator::Validate;

/// Request to enable TOTP (verifies the first code after setup)
#[derive(Debug, Deserialize, Validate, ToSchema)]
#[schema(description = "Request body for enabling TOTP after the setup step.")]
pub struct TotpEnableRequest {
    /// 6-digit TOTP code generated by the authenticator app
    #[validate(length(equal = 6, message = "TOTP code must be 6 digits"))]
    pub code: String,
}
