version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_MODE: ${BUILD_MODE:-}
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    environment:
      RUST_LOG: ${RUST_LOG:-info}
      HOST: 0.0.0.0
    restart: unless-stopped