allowBuilds:
  '@tailwindcss/oxide': true
  workerd: true
  sharp: true
  esbuild: true
minimumReleaseAgeExclude:
  - '@levish0/lily-pad@0.3.0'
  - '@levish0/lily-pad@0.3.1'
patchedDependencies:
  '@levish0/lily-pad': patches/@levish0__lily-pad.patch
